# Generated by Django 5.2.7 on 2025-10-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('interests', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
